# Training configuration for ResNet trained on ImageNet on GPUs.
# Reaches > 76.1% within 90 epochs.
# Note: This configuration uses a scaled per-replica batch size based on the number of devices.
runtime:
  distribution_strategy: 'multi_worker_mirrored'
  batchnorm_spatial_persistent: True
  enable_xla: True
train_dataset:
  name: 'imagenet2012'
  data_dir: null
  builder: 'records'
  split: 'train'
  image_size: 224
  num_classes: 1000
  num_examples: 1281167
  batch_size: 256
  use_per_replica_batch_size: True
  dtype: 'float16'
  mean_subtract: True
  standardize: True
validation_dataset:
  name: 'imagenet2012'
  data_dir: null
  builder: 'records'
  split: 'validation'
  image_size: 224
  num_classes: 1000
  num_examples: 50000
  batch_size: 256
  use_per_replica_batch_size: True
  dtype: 'float16'
  mean_subtract: True
  standardize: True
model:
  name: 'resnet'
  model_params:
    rescale_inputs: False
  optimizer:
    name: 'momentum'
    momentum: 0.9
    decay: 0.9
    epsilon: 0.001
  loss:
    label_smoothing: 0.1
train:
  resume_checkpoint: False
  epochs: 20
  callbacks:
    enable_checkpoint_and_export: False
    backup_dir: "s3://sam-debug-binaries/elastic/backup"
evaluation:
  epochs_between_evals: 100
  skip_eval: True


